---
# tasks file for apache
- name: ensure that '{{ apache_package }}' package is installed
  yum:
          name: '{{ apache_package }}'
          state: latest

- name: ensure that '{{ apache_service }}' service is enabled and started
  service:
          name: '{{ apache_service }}'
          state: started
          enabled: true

- name: ensure that firewalld service is enabled and started
  service:
          name: firewalld
          state: started
          enabled: true

- name: ensure that web server access is allowed via firewalld
  firewalld:
          service: '{{ item }}'
          immediate: yes
          permanent: yes
          state: enabled
  loop: '{{ web_services }}' 

- name: deploying a template on web path
  template:
          src: index.html.j2
          dest: /var/www/html/index.html
  notify:
          - restart apache service
