---
- name: adding admin ssh public key to managed nodes
  hosts: all

  tasks:
          - name: adding ssh public key
            authorized_key:
                    user: admin
                    state: present
                    key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

